server:
  port: 8080
spring:
  application:
    name: spring-boot-application
  datasource:
    url: jdbc:mysql://192.168.62.181:3306/ruoyi_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: cezitime
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    serialization:
      indent-output: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
#    ????
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    map-underscore-to-camel-case: true
